// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIer9scRIyfDF0XWZRR8z4Fgou5Un4qY4',
    appId: '1:67185230646:web:9eba894b20bb306e49a997',
    messagingSenderId: '67185230646',
    projectId: 'stock1app',
    authDomain: 'stock1app.firebaseapp.com',
    storageBucket: 'stock1app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6O7V3QTgkX95wOoEH7C6evX49IUI_xt0',
    appId: '1:67185230646:android:8631f06243b49d5d49a997',
    messagingSenderId: '67185230646',
    projectId: 'stock1app',
    storageBucket: 'stock1app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACwMu-pfbtFjy4KASVvZOQ4ymXUY-ljzo',
    appId: '1:67185230646:ios:a01e7ab74c3efc6449a997',
    messagingSenderId: '67185230646',
    projectId: 'stock1app',
    storageBucket: 'stock1app.firebasestorage.app',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACwMu-pfbtFjy4KASVvZOQ4ymXUY-ljzo',
    appId: '1:67185230646:ios:a01e7ab74c3efc6449a997',
    messagingSenderId: '67185230646',
    projectId: 'stock1app',
    storageBucket: 'stock1app.firebasestorage.app',
    iosBundleId: 'com.example.proj2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIer9scRIyfDF0XWZRR8z4Fgou5Un4qY4',
    appId: '1:67185230646:web:df2b82448d4a43b049a997',
    messagingSenderId: '67185230646',
    projectId: 'stock1app',
    authDomain: 'stock1app.firebaseapp.com',
    storageBucket: 'stock1app.firebasestorage.app',
  );
}
